---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(splines)
library(splines2)
library(tidyverse)
library(coro)
library(gridExtra)
library(ggtext)
library(segmented)
library(changepoint)
library(spatstat.geom) # crossdist function in cpa.find_closest_point
library(matrixStats)
library(scales)
```

```{r}
# source files
source_files <- list.files("./src/script", full.names = TRUE, pattern = "*.R")
map(paste0(source_files), source)

area <- read_csv("data/area.csv")
```


```{r}
bone <- data.fetch(subject.name = "pf14CP1")
spline_model <- lm(Stress ~ bSpline(Strain, df = 10), data = bone %>% filter(Strain < 0.2))

spline_fit <- predict(spline_model)
spline_fit <- append(spline_fit, rep(NA, length.out = length(bone) - length(spline_fit)))
ggplot(bone, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal()

mt01spline_model <- lm(Stress ~ ns(Strain, df = 10), data = pf09mt01)

pf09mt01$spline_fit <- predict(mt01spline_model)
ggplot(pf09mt01, aes(x = Strain)) + #Tg
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal()
```


```{r}
loop(for (fish in data.generator("./data", 9)) {
  #fish <- fish %>% filter(Strain < 0.2)
  basis_mat <- ns(fish$Strain, df = 15)
  spline_model <- lm(Stress ~ basis_mat, data = fish)
  fish$spline_fit <- predict(spline_model)
  plot <- ggplot(fish, aes(x = Strain)) +
    geom_point(aes(y = Stress)) +
    geom_line(aes(y = spline_fit), color = "blue") + 
    theme_minimal()
  
  print(paste("Fish number: ", fish$Individual, ", Segment: ",  fish$Segment, ", Trial Number: ", fish$Trial, sep = ""))
  print(plot)
  break
})
```



```{r}
cp01spline_model <- lm(Stress ~ ns(Strain, df = 10), data = pf09cp01)

# Create a sequence of values for Strain for prediction
strain_seq <- seq(min(pf09cp01$Strain), max(pf09cp01$Strain), length.out = 500)

# Predict fitted values
fitted_values <- predict(cp01spline_model, newdata = data.frame(Strain = strain_seq))

# Calculate numerical derivatives
# Using finite difference method for derivative
delta <- 1e-8  # A small number for numerical differentiation
predicted_derivative <- (predict(cp01spline_model, newdata = data.frame(Strain = strain_seq + delta)) -
                          predict(cp01spline_model, newdata = data.frame(Strain = strain_seq - delta))) / (2 * delta)

predicted_second_derivative <- (predict(cp01spline_model, newdata = data.frame(Strain = strain_seq + delta)) +
                                  predict(cp01spline_model, newdata = data.frame(Strain = strain_seq - delta)) -
                                  2 * fitted_values) / (delta^2)

# Combine results
results <- data.frame(Strain = strain_seq, Fitted = fitted_values, 
                      First_Derivative = predicted_derivative, 
                      Second_Derivative = predicted_second_derivative)

# View the results
head(results)
```

#Splines2

https://stats.stackexchange.com/a/635096 dbs() method explained and used here.


```{r}
modeli <- lm(Stress ~ bSpline(Strain, df = 20), data = pf09cp01)

pf09cp01$spline_fit <- predict(model)
ggplot(pf09cp01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal()

coefs <- coef(model)
first_deriv_matrix <- dbs(pf09cp01$Strain, df = 20, derivs = 1)
pf09cp01$first_deriv <- first_deriv_matrix %*% coefs[-1]

second_deriv_matrix <- dbs(pf09cp01$Strain, df = 20, derivs = 2)
pf09cp01$second_deriv <- second_deriv_matrix %*% coefs[-1]
```

#pf09cp01
```{r}
df=10

pf09cp01short <- pf09cp01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = df), data = pf09cp01short)
coefs_short <- coef(model)

pf09cp01short$spline_fit <- predict(model)
ggplot(pf09cp01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.026923077) +                   # deriv = 177
  geom_vline(xintercept = 0.030769231, color = "red")      # deriv = 169

first_deriv_matrix <- dbs(pf09cp01short$Strain, df = df, derivs = 1)
pf09cp01short$first_deriv <- first_deriv_matrix %*% coefs_short[-1]

second_deriv_matrix <- dbs(pf09cp01short$Strain, df = df, derivs = 2)
pf09cp01short$second_deriv <- second_deriv_matrix %*% coefs_short[-1]
```


#pf09lt01
```{r}
pf09lt01 <- read_tsv("data/pf09/pf09lt01.csv",
skip = 15)

area = 3.203110e-06
length_initial = 3.00
load = 0.8
data_clean(pf09lt01, area, length_initial, load)

pf09lt01short <- pf09lt01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09lt01short)
coefs_short <- coef(model)

pf09lt01short$spline_fit <- predict(model)
ggplot(pf09lt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.040000000)            # deriv = 115

first_deriv_matrix <- dbs(pf09lt01short$Strain, df = 10, derivs = 1)
pf09lt01short$first_deriv <- first_deriv_matrix %*% coefs_short[-1]

second_deriv_matrix <- dbs(pf09lt01short$Strain, df = 10, derivs = 2)
pf09lt01short$second_deriv <- second_deriv_matrix %*% coefs_short[-1]
```

#pf09ut01

```{r}
pf09ut01 <- read_tsv("data/pf09/pf09ut01.csv",
skip = 15)

area = 5.064510e-06
length_initial = 3.05
load = 0.8
data_clean(pf09ut01, area, length_initial, load)

pf09ut01short <- pf09ut01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09ut01short)
coefs_short <- coef(model)

pf09ut01short$spline_fit <- predict(model)
ggplot(pf09ut01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.059016393) +              # deriv = 157
  geom_vline(xintercept = 0.078688525, color = "red") # deriv = 80

first_deriv_matrix <- dbs(pf09ut01short$Strain, df = 10, derivs = 1)
pf09ut01short$first_deriv <- first_deriv_matrix %*% coefs_short[-1]

second_deriv_matrix <- dbs(pf09ut01short$Strain, df = 10, derivs = 2)
pf09ut01short$second_deriv <- second_deriv_matrix %*% coefs_short[-1]
```



```{r}
#pf0mtt01
pf09mt01 <- read_tsv("data/pf09/pf09mt01.csv",
skip = 15)

area = 0.00000793823
length_initial = 2.82
load = 0.8
data_clean(pf09mt01, area, length_initial, load)

pf09mt01short <- pf09mt01 %>%
  filter(Strain < 0.2)

model_mt <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09mt01short)
coefs_short <- coef(model_mt)

pf09mt01short$spline_fit <- predict(model_mt)
ggplot(pf09mt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = (0.042553191 + 0.039007092) / 2) # deriv = 48

first_deriv_matrix <- dbs(pf09mt01short$Strain, df = 10, derivs = 1)
pf09mt01short$first_deriv <- first_deriv_matrix %*% coefs_short[-1]

second_deriv_matrix <- dbs(pf09mt01short$Strain, df = 10, derivs = 2)
pf09mt01short$second_deriv <- second_deriv_matrix %*% coefs_short[-1]
```

9833



# Derivative of Functions Exploration

#pf09

```{r}
pf09cp01 <- read_tsv("data/pf09/pf09cp01.csv", skip = 15)

area = 3.203110e-06
length_initial = 2.60
load = 0.8
data_clean(pf09cp01, area, length_initial, load)

pf09cp01 <- pf09cp01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf09cp01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf09cp01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf09cp01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf09lt01 <- read_tsv("data/pf09/pf09lt01.csv",
skip = 15)

area = 3.203110e-06
length_initial = 3.00
load = 0.8
data_clean(pf09lt01, area, length_initial, load)

pf09lt01 <- pf09lt01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf09lt01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf09lt01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf09lt01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf09mt01 <- read_tsv("data/pf09/pf09mt01.csv",
skip = 15)

area = 0.00000793823
length_initial = 2.82
load = 0.8
data_clean(pf09mt01, area, length_initial, load)

pf09mt01 <- pf09mt01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf09mt01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf09mt01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf09mt01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf09ut01 <- read_tsv("data/pf09/pf09ut01.csv",
skip = 15)

area = 5.064510e-06
length_initial = 3.05
load = 0.8
data_clean(pf09ut01, area, length_initial, load)

pf09ut01 <- pf09ut01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf09ut01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf09ut01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf09ut01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()

```

#pf06
```{r}
pf06cp01 <- read_tsv("data/pf06/pf06cp01.csv", skip = 15)

area = 3.203110e-06
length_initial = 2.60
load = 0.8
data_clean(pf06cp01, area, length_initial, load)

pf06cp01 <- pf06cp01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf06cp01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf06cp01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf06cp01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf06lt01 <- read_tsv("data/pf06/pf06lt01.csv",
skip = 15)

area = 3.203110e-06
length_initial = 3.00
load = 0.8
data_clean(pf06lt01, area, length_initial, load)

pf06lt01 <- pf06lt01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf06lt01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf06lt01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf06lt01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf06mt01 <- read_tsv("data/pf06/pf06mt01.csv",
skip = 15)

area = 0.00000793823
length_initial = 2.82
load = 0.8
data_clean(pf06mt01, area, length_initial, load)

pf06mt01 <- pf06mt01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf06mt01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf06mt01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf06mt01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()
```

```{r}
pf06ut01 <- read_tsv("data/pf06/pf06ut01.csv",
skip = 15)

area = 5.064510e-06
length_initial = 3.05
load = 0.8
data_clean(pf06ut01, area, length_initial, load)

pf06ut01 <- pf06ut01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2)))

ggplot(pf06ut01, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  theme_minimal()

ggplot(pf06ut01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  theme_minimal()

ggplot(pf06ut01, aes(x = Strain)) +
  geom_point(aes(y = second_deriv)) +
  theme_minimal()

```

#Splining Derivatives

```{r}
pf09cp01 <- read_tsv("data/pf09/pf09cp01.csv", skip = 15)

area = 3.203110e-06
length_initial = 2.60
load = 0.8
data_clean(pf09cp01, area, length_initial, load)

pf09cp01 <- pf09cp01 %>%
  mutate(first_deriv = (Stress - lag(Stress, 2)) / (Strain - lag(Strain, 2)),
         second_deriv = (first_deriv - lag(first_deriv, 2)) / (Strain - lag(Strain, 2))) %>%
  filter(!is.na(first_deriv), is.finite(first_deriv))

model1 <- lm(first_deriv ~ bSpline(Strain, df = 15), data = pf09cp01)
coefs_short1 <- coef(model1)

pf09cp01$spline_fit <- predict(model1)
ggplot(pf09cp01, aes(x = Strain)) +
  geom_point(aes(y = first_deriv)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal()

first_deriv_matrix <- dbs(pf09cp01short$Strain, df = df, derivs = 1)
pf09cp01short$first_deriv <- first_deriv_matrix %*% coefs_short[-1]

second_deriv_matrix <- dbs(pf09cp01short$Strain, df = df, derivs = 2)
pf09cp01short$second_deriv <- second_deriv_matrix %*% coefs_short[-1]

```




