---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

theme_set(theme_classic())

source("./src/script/youngsModulus/youngsModulus.R")
source("./src/script/youngsModulus/youngsModulusDetermination.R")
source("./src/script/youngsModulus/windowSearch.R")
source("./src/script/helpers/data.R")
source("./src/script/helpers/plot.R")
source("./src/script/helpers/image.R")
```

```{r}
b1 <- data.fetch(subject.name = "pf01cp1")
w1 <- ws.calculate(b1)

w1 <- w1 %>% 
  mutate(slope = map_dbl(window.fit, ~ coefficients(.x)[[2]])) %>% 
  na.omit()

w1 %>% 
  ggplot(aes(x = Strain, y = slope)) + 
  geom_point() +
  geom_line()

(sd <- sd(w1$slope))

w1 %>% 
  ggplot(aes(x = slope)) + 
  geom_histogram(fill = "orange") + 
  geom_vline(xintercept = c(sd, -sd), color = "red") + 
  geom_vline(xintercept = c(2 * sd, 2 * -sd), color = "purple")

```



## saving results
```{r}
bones <- data.generator()
```

```{r}
names <- vector()
slopes <- vector()
rmses <- vector()
strains <- vector()
```

```{r}
do.plot <- TRUE
do.save <- FALSE
for (bone in bones) {
  result <- ws.calculate(bone)
  if (is.null(result$model)) {
    message(getName(bone), ": Could not calculate slope")
    next
  }
  
  names <- append(names, result$name)
  slopes <- append(slopes, result$slope)
  rmses <- append(rmses, result$rmse)
  strains <- append(strains, result$strain)
  
  plot <- NULL
  if (do.plot || do.save) {
    layers <- c(
      geom_abline(slope = result$slope,
                    intercept = coefficients(result$model)[[1]],
                    color = "red",
                    show.legend = FALSE),
        geom_vline(xintercept = result$strain, color = "blue", show.legend = FALSE)
      )
    plot <- plot.plot(bone, layers)
  }
  
  if (do.plot) {
    print(plot)
  }
  
  if (do.save) {
    image.save(bone, plot, directory = "ymResults/windowSearch")
  }
}
```

```{r}
results <- tibble(names, slope = slopes, strain = strains, rmse = rmses)
write_csv(results, "./results/youngsModulus/windowResults.csv")
```


