---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
source("./src/script/youngsModulus/youngsModulusDetermination.R")
source("./src/script/youngsModulus/youngsModulus.R")
source("./src/script/helpers/data.R")
source("./src/script/helpers/general.R")
source("./src/script/plot.R")
source("./src/script/image.R")
```

```{r}
var <- ym.calculateAndDetermine(data.fetch(subject.name = "pf09lt2"))
```



```{r}
bones <- data.generator()
names <- vector(length = 273)
method <- vector(length = 273)
calculation <- vector(length = 273)
slope <- vector(length = 273)
score <- vector(length = 273)
strain <- vector(length = 273)
rsquared <- vector(length = 273)
inconclusive <- vector(length = 273)
```

```{r}
doPlot <- FALSE
doSave <- FALSE

i <- 1
for (bone in bones) {
  ym.result <- ym.calculate(bone)
  if (is.null(ym.result)) next
  choose <- ym.determine(ym.result)
  
  name <- getName(bone)
  names[i] <- name
  method[i] <- choose$method
  calculation[i] <- choose$calculation
  slope[i] <- choose$slope
  score[i] <- choose$score
  strain[i] <- choose$strain
  rsquared[i] <- ym.result$r.squared
  inconclusive[i] <- choose$inconclusive
  i <- i + 1
  
  if (doPlot || doSave) {
    plot.subtitle <- paste(
      "<b>Method:</b> ",
      choose$method,
      "<br>",
      "<b>Slope:</b>",
      round(choose$slope, 1),
      "<br>",
      "<b>Score</b>",
      round(choose$score, 3),
      "<br>",
      "<b>R-squared:</b>",
      round(ym.result$r.squared, 1),
      "<br>"
    )
    
    plot <- plot.plot(
      bone,
      layers = list(
        geom_segment(
          x = choose$strain,
          xend = choose$strain,
          y = 0,
          yend = max(bone$Stress),
          color = "red"
        ),
        labs(subtitle = plot.subtitle)
      )
    )
    
    if(doPlot) {
      print(plot)
    }
  }
  
  if (doSave) {
    image.save(bone, plot, directory = "ymResults/decisions")
  }
  
}
```

```{r}
results <- data.frame(names, method, calculation, slope, score, strain, rsquared, inconclusive)
write_csv(results, "results/youngsModulus/decisions_2.csv")
```


