---
title: "statistical_analysis"
author: "Abby Hahs, Ansel Alldredge, Otto Schmidt"
output: pdf_document
date: "2025-02-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(coro)
library(gridExtra)
library(ggtext)
library(segmented)
library(changepoint)
library(matrixStats)
library(scales)
library(stats)
library(readr)
library(lme4)

setwd("/home/rstudio/users/hahs1/CIR_2024_25_Fish_Vertebrae")
data_directory <- "./data"
script_directory <- "./src/script/"
```

```{r}
yieldStress <- read_csv("results/yieldStress/yieldStress.csv")
method <- read_csv("results/youngsModulus/results.csv")
misidentified <- c("pf13UT4", "pf15CP1", "pf15LT1", "pf20UT4", "pf21UT1", "sv01UT1", "sv01UT2", "pf04UT2", "pf05UT2", "pf06CP1", "pf06UT1", "pf07LT1")

yieldstress_good <- yieldStress |>
         filter(!(names %in% misidentified)) |>
  mutate(fish_type = str_sub(names, 1, 2), 
         fish_num = str_sub(names, 3, 4), 
         bone_type = str_sub(names, 5, 6), 
         bone_num = str_sub(names, 7, 8),
         fish_name = str_sub(names, 1, 4)) |>
  filter(fish_type != "sv")

```

# Yield stress

```{r}
a1 <- aov(yield.stress ~ bone_type, data = yieldstress_good)
summary(a1) # p < 0.001

TukeyHSD(a1) 
# LT-CP, MT-CP, UT-LT, UT-MT, 
# not UT-CP, MT-LT
```







