---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
source("./src/script/youngsModulus/youngsModulusDetermination.R")
source("./src/script/youngsModulus/youngsModulus.R")
source("./src/script/helpers/data.R")
source("./src/script/helpers/general.R")
source("./src/script/helpers/plot.R")
source("./src/script/helpers/image.R")
```

```{r}
var <- ym.calculateAndDetermine(data.fetch(subject.name = "pf02ut3"))
```



```{r}
bones <- data.generator()
```

```{r}
names <- vector()
methods <- vector()
calculations <- vector()
slopes <- vector()
scores <- vector()
strains <- vector()
rsquareds <- vector()
inconclusives <- vector()

doPlot <- FALSE
doSave <- FALSE

i <- 1
for (bone in bones) {
  choose <- ym.calculateAndDetermine(bone)$choice
  if (is.null(choose)) next
  
  slope <- choose$slope[[1]]
  score <- choose$score[[1]]
  strain <- choose$strain[[1]]

  name <- getName(bone)
  names[i] <- name
  methods[i] <- choose$method
  calculations[i] <- choose$calculation
  slopes[i] <- slope
  scores[i] <- score
  strains[i] <- strain
  rsquareds[i] <- ym.result$r.squared
  inconclusives[i] <- choose$inconclusive
  i <- i + 1
  
  if (doPlot || doSave) {
    plot.subtitle <- paste(
      "<b>Method:</b> ",
      choose$method,
      "<br>",
      "<b>Slope:</b>",
      round(slope, 1),
      "<br>",
      "<b>Score</b>",
      round(score, 3),
      "<br>",
      "<b>R-squared:</b>",
      round(ym.result$r.squared, 1),
      "<br>"
    )
    
    plot <- plot.plot(
      bone,
      layers = list(
        geom_segment(
          x = strain,
          xend = strain,
          y = 0,
          yend = max(bone$Stress),
          color = "red"
        ),
        labs(subtitle = plot.subtitle)
      )
    )
    
    if(doPlot) {
      print(plot)
    }
  }
  
  if (doSave) {
    image.save(bone, plot, directory = "ymResults/decisions")
  }
}
```

```{r}
results <- data.frame(
  name = names,
  method = methods,
  calculation = calculations,
  slope = slopes,
  score = scores,
  strain = strains,
  rsquared = rsquareds,
  inconclusive = inconclusives
)
write_csv(results, "results/youngsModulus/decisions.csv")
```

```{r}
results %>% filter(calculations == "max") %>% dplyr::select(names, inconclusives)
```



