---
title: "main"
author: "Abby Hahs, Ansel Alldredge, Otto Schmidt"
date: "2024-09-18"
output: pdf
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(coro)
library(gridExtra)
library(ggtext)
library(segmented)
library(changepoint)
library(spatstat.geom) # crossdist function in cpa.find_closest_point
library(matrixStats)
library(scales)
#library(ggdark) 

setwd("/home/rstudio/users/hahs1/CIR_2024_25_Fish_Vertebrae")
data_directory <- "./data"
script_directory <- "./src/script/"
```

## Source files. re-run this chunk when you make changes to any .R file
```{r}
# this will pick up any .R files added to the src/script directory. remember to re-run
source_files <- list.files(script_directory, full.names = TRUE, pattern = "*.R")
map(paste0(source_files), source)
```

## Test fish
```{r}
test_data_iterator <- data.generator(data_directory)
test_fish <- test_data_iterator()
test_data_iterator <- NULL # throw away the iterator
```

# Change point analysis

## Segmentation and finding the slope between predicted break points
```{r}
loop(for (fish in data.generator(data_directory)) {
  fit_segmented <- cpa.segment(fish, 10) # n is arbitrary. for our purposes, higher (10) is better because we want more resolution
  print(summary(fit_segmented))
  nearest_points <- cpa.nearest_points(fish, fit_segmented)
  print(plot.predicted(fish, fit_segmented, nearest_points))
  #slopes <- cpa.slope(nearest_points)
  #break
})
```

# Images 

Save all images

```{r}
data_iterator <- data.generator(data_directory)

loop(for (fish in data_iterator) {
  image.save(fish, plot(fish))
})
```


