---
title: "max_slope"
output: pdf_document
date: "2024-11-06"
editor_options: 
  chunk_output_type: console
---

```{r}
library(splines)
library(splines2)
library(tidyverse)
library(dplyr)
library(coro)
library(gridExtra)
library(ggtext)
library(segmented)
library(changepoint)
library(spatstat.geom) # crossdist function in cpa.find_closest_point
library(matrixStats)
library(scales)

setwd("/home/rstudio/users/hahs1/CIR_2024_25_Fish_Vertebrae")
data_directory <- "./data"
script_directory <- "./src/script/"
```

```{r}
# source files
source_files <- list.files("./src/script", full.names = TRUE, pattern = "*.R")
map(paste0(source_files), source)
```

```{r}
area <- read_csv("data/area.csv")
```

```{r}
pf09cp01 <- data.fetch(subject = "pf09cp1")
pf09lt01 <- data.fetch(subject = "pf09lt1")
pf09ut01 <- data.fetch(subject = "pf09ut1")
pf09mt01 <- data.fetch(subject = "pf09mt1")
pf10cp01 <- data.fetch(subject = "pf10cp1")
pf19mt01 <- data.fetch(subject = "pf19mt1")
pf19cp01 <- data.fetch(subject = "pf19cp1")
pf16cp01 <- data.fetch(subject = "pf16cp1")
pf17mt01 <- data.fetch(subject = "pf17mt1")
pf16ut01 <- data.fetch(subject = "pf16ut1")
pf03lt01 <- data.fetch(subject = "pf03lt1")
pf07ut01 <- data.fetch(subject = "pf07ut1")
pf16lt01 <- data.fetch(subject = "pf16lt1")

fish_list <- list(pf09cp01,pf09lt01,pf09ut01,pf09mt01,pf10cp01,pf19mt01,pf19cp01,pf16cp01,pf07mt01,pf16ut01,pf03lt01, pf07ut01)
```


# Use splines package to find the maximum first derivative left of 0.2 strain


>> pf09cp01

```{r}
pf09cp01short <- pf09cp01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09cp01short)
coefs_short <- coef(model)

pf09cp01short$spline_fit <- predict(model)
ggplot(pf09cp01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.023076923, color = "red") +          # deriv = 220.
  geom_vline(xintercept = 0.023076923, color = "purple") # deriv = 178
  
# derivative of grid
n <- nrow(pf09cp01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf09cp01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf09cp01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf09cp01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# look at first deriv near when the concavity switches
# 180.5
```

>> pf09lt01

```{r}
pf09lt01short <- pf09lt01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09lt01short)
coefs_short <- coef(model)

pf09lt01short$spline_fit <- predict(model)
ggplot(pf09lt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.036666667 , color = "red")    # deriv = 112
  
n <- nrow(pf09lt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf09lt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf09lt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf09lt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 116.1
```

>> pf09ut01

```{r}
pf09ut01short <- pf09ut01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09ut01short)
coefs_short <- coef(model)

pf09ut01short$spline_fit <- predict(model)
ggplot(pf09ut01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.0557377, color = "red") + # deriv = 158.4
  geom_vline(xintercept = 0.059016393, color = "green") # 151.97233

n <- nrow(pf09ut01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf09ut01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf09ut01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]


# max deriv
pf09ut01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# same, 158.4
```

>> pf09mt01

```{r}
pf09mt01short <- pf09mt01 %>%
  filter(Strain < 0.2)

model_mt <- lm(Stress ~ bSpline(Strain, df = 10), data = pf09mt01short)
coefs_short <- coef(model_mt)

pf09mt01short$spline_fit <- predict(model_mt)
ggplot(pf09mt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.04255319, color = "red") + # deriv = 48.9
  geom_vline(xintercept = 0.042553191, color = "green") # 48.215526

n <- nrow(pf09mt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf09mt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf09mt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf09mt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# same, 48.9
```

>>pf10cp01

```{r}
pf10cp01short <- pf10cp01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf10cp01short)
coefs_short <- coef(model)

pf10cp01short$spline_fit <- predict(model)
ggplot(pf10cp01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.03960396, color = "red")          # deriv = 43.6
  
  
n <- nrow(pf10cp01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf10cp01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf10cp01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf10cp01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# look at first deriv near when the concavity switches
# 43.6
```

>>pf19mt01

```{r}
pf19mt01short <- pf19mt01 %>%
  filter(Strain < 0.2)

model_mt <- lm(Stress ~ bSpline(Strain, df = 10), data = pf19mt01short)
coefs_short <- coef(model_mt)

pf19mt01short$spline_fit <- predict(model_mt)
ggplot(pf19mt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.08487085, color = "red") + # deriv = 118.9
  geom_vline(xintercept = 0.044280443, color = "purple") # deriv = 71.4
  
n <- nrow(pf19mt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf19mt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf19mt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]


# max deriv
pf19mt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 71.4
```

>>pf19cp01

```{r}
pf19cp01short <- pf19cp01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf19cp01short)
coefs_short <- coef(model)

pf19cp01short$spline_fit <- predict(model)
ggplot(pf19cp01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.1834061 , color = "red") + # deriv = 100.6
  geom_vline(xintercept = 0.034934498, color = "purple") # deriv = 82.6
  
n <- nrow(pf19cp01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf19cp01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf19cp01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf19cp01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 82.6
```


>>pf16cp01

```{r}
pf16cp01short <- pf16cp01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf16cp01short)
coefs_short <- coef(model)

pf16cp01short$spline_fit <- predict(model)
ggplot(pf16cp01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.0483871  , color = "red")  # deriv = 122.6
  
  
n <- nrow(pf16cp01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf16cp01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf16cp01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf16cp01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 122.6
```

>> pf07mt01

```{r}
pf07mt01short <- pf07mt01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf07mt01short)
coefs_short <- coef(model)

pf07mt01short$spline_fit <- predict(model)
ggplot(pf07mt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.04285714, color = "red")  # deriv = 110.6
 
  
n <- nrow(pf07mt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf07mt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf07mt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf07mt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 110.6
```

>>pf16ut01

```{r}
pf16ut01short <- pf16ut01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf16ut01short)
coefs_short <- coef(model)

pf16ut01short$spline_fit <- predict(model)
ggplot(pf16ut01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.1036789  , color = "red") +  # deriv = 157.1
  geom_vline(xintercept = 0.016722408, color = "purple") # 16.3
  
n <- nrow(pf16ut01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))
pf16ut01short$strain_grid <- strain_grid

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf16ut01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf16ut01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf16ut01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 16.3
```


>> pf03lt01

```{r}
pf03lt01short <- pf03lt01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf03lt01short)
coefs_short <- coef(model)

pf03lt01short$spline_fit <- predict(model)
ggplot(pf03lt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.02415459, color = "red")  # deriv = 95.6
 
n <- nrow(pf03lt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf03lt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf03lt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf03lt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 95.6
```

>> pf07ut01

```{r}
pf07ut01short <- pf07ut01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf07ut01short)
coefs_short <- coef(model)

pf07ut01short$spline_fit <- predict(model)
ggplot(pf07ut01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.04591837 , color = "red")  # deriv = 154.2
  
  
n <- nrow(pf07ut01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf07ut01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf07ut01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf07ut01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 154.2
```

>> pf16lt01

```{r}
pf16lt01short <- pf16lt01 %>%
  filter(Strain < 0.2)

model <- lm(Stress ~ bSpline(Strain, df = 10), data = pf16lt01short)
coefs_short <- coef(model)

pf16lt01short$spline_fit <- predict(model)
ggplot(pf16lt01short, aes(x = Strain)) +
  geom_point(aes(y = Stress)) +
  geom_line(aes(y = spline_fit), color = "blue") + 
  theme_minimal() +
  geom_vline(xintercept = 0.02848101  , color = "red")  # deriv = 150.7
  
  
n <- nrow(pf16lt01short)

strain_grid <- seq(0, 0.2, (0.2/(n-1)))

first_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 1)
second_deriv_matrix_grid <- dbs(strain_grid, df = 10, derivs = 2)

pf16lt01short$first_deriv <- first_deriv_matrix_grid %*% coefs_short[-1]
pf16lt01short$second_deriv <- second_deriv_matrix_grid %*% coefs_short[-1]

# max deriv
pf16lt01short |>
  slice_max(first_deriv, n = 1) |>
  dplyr::select(Strain, first_deriv, second_deriv) |>
  as.data.frame()

# max deriv near 2nd deriv = 0
# 150.7
```

## Trying MARS package

```{r}
library(earth)
library(tidymodels)
library(gridExtra)
```

```{r}
pf07ut01short <- pf07ut01|>
  filter(Strain < 0.2)

set.seed(12345)
split <- initial_split(pf07ut01short, prop = 0.8)
train <- training(split)
test <- testing(split)

folds <- vfold_cv(train, v = 10)
grid <- grid_regular(num_terms(range = c(1, 11)), levels = 10)

mars_model <- mars(num_terms = tune()) |>
  set_engine("earth") |>
  set_mode("regression")

mars_recipe <- recipe(Stress ~ Strain, data = train)

mars_wf <- workflow() |>
  add_model(mars_model) |>
  add_recipe(mars_recipe)

tune_results <- tune_grid(object = mars_wf,
                          resamples = folds,
                          grid = grid)

autoplot(tune_results)

show_best(tune_results, metric = "rmse")

best_neighbor <- select_by_one_std_err(tune_results, metric = "rmse", num_terms)

mars_final_wf <- finalize_workflow(mars_wf, best_neighbor)
mars_final_fit <- fit(mars_final_wf, train)

augment(mars_final_fit, test) |>
  ggplot() +
  geom_point(aes(x = Strain, y = Stress)) + 
  geom_line(aes(x = Strain, y = .pred, color = "red"))

augment(mars_final_fit, test) |>
  rsq(Stress, .pred)

extract_fit_engine(mars_final_fit) |>
  summary()
```


```{r}
pf09mt01short <- pf09mt01|>
  filter(Strain < 0.2)

set.seed(12345)
split <- initial_split(pf09mt01short, prop = 0.8)
train <- training(split)
test <- testing(split)

folds <- vfold_cv(train, v = 10)
grid <- grid_regular(num_terms(range = c(1, 11)), levels = 10)

mars_model <- mars(num_terms = tune()) |>
  set_engine("earth") |>
  set_mode("regression")

mars_recipe <- recipe(Stress ~ Strain, data = train)

mars_wf <- workflow() |>
  add_model(mars_model) |>
  add_recipe(mars_recipe)

tune_results <- tune_grid(object = mars_wf,
                          resamples = folds,
                          grid = grid)

autoplot(tune_results)

show_best(tune_results, metric = "rmse")

best_neighbor <- select_by_one_std_err(tune_results, metric = "rmse", num_terms)

mars_final_wf <- finalize_workflow(mars_wf, best_neighbor)
mars_final_fit <- fit(mars_final_wf, train)

augment(mars_final_fit, test) |>
  ggplot() +
  geom_point(aes(x = Strain, y = Stress)) + 
  geom_line(aes(x = Strain, y = .pred, color = "red"))

augment(mars_final_fit, test) |>
  rsq(Stress, .pred)

extract_fit_engine(mars_final_fit) |>
  summary()
```
