---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)

source("./src/script/youngsModulus.R")
source("./src/script/data.R")
source("./src/script/plot.R")
source("./src/script/image.R")
```


## slope variability index

The Slope Variability Index measures the variation of slopes with reference to the selected slope for a window of 201 first derivative values.

SVI indicators:
  1. Two methods have the same, near 0
  2. One method has a score near 0
```{r}
#pf06cp3: two are similar and near 0
pf06cp3 <- data.fetch(fish_numbers = c(6), segments = c("cp"), trials = c(3))
pf06cp3.result1 <- ym.calculate(pf06cp3)

pf06cp3.result1$max.score # same, 0
pf06cp3.result1$inflection.score # same, 0
pf06cp3.result1$fds.score

# pf01cp1: all are similar
pf01cp1 <- data.fetch(fish_numbers = c(1), segments = c("cp"), trials = c(1))
pf01cp1.result <- ym.calculate(pf01cp1)

pf01cp1.result$max.score
pf01cp1.result$inflection.score
pf01cp1.result$fds.score

# pf02cp2: one is near 0 and in the right place according to the decision tree
pf01cp2 <- data.fetch(fish_numbers = c(1), segments = c("cp"), trials = c(2))
pf01cp2.result <- ym.calculate(pf01cp2)

pf01cp2.result$max.score 
pf01cp2.result$inflection.score # 0
pf01cp2.result$fds.score
```


## troublemakers

### can't fit
```{r}
# can't fit spline
pf09ut4 <- data.fetch(fish_numbers = c(9), segments = c("ut"), trials = c(4))
pf09ut4.max <- ym.calculate(pf09ut4)
plot.subject("9ut4") # initial noise

# can't fit all 10 knots (fit 8).
pf15cp2 <- data.fetch(fish_numbers = c(15), segments = c("cp"), trials = c(2))
pf15cp2.inflection <- ym.calculate(pf15cp2, method = "inflection")
plot.subject("15cp2") # like 10 observations

# can't fit spline
pf20lt3 <- data.fetch(fish_numbers = c(20), segments = c("lt"), trials = c(3))
pf20lt3.max <- ym.calculate(pf20lt3, method = "max")
plot.subject("20lt3") # initial noise
```


## saving results
```{r}
names <- vector()
rsquared <- vector()
max.slope <- vector()
max.strain <- vector()
max.score <- vector()
inflection.slope <- vector()
inflection.strain <- vector()
inflection.score <- vector()
fds.slope <- vector()
fds.strain <- vector()
fds.score <- vector()

loop(for (bone in data.generator()) {
  result <- ym.calculate(bone)
  if (is.null(result)) next
  
  names <- append(names, result$name)
  rsquared <- append(rsquared, result$r.squared)
  max.slope <- append(max.slope, result$max.slope)
  max.strain <- append(max.strain, result$max.strain)
  max.score <- append(max.score, result$max.score)
  inflection.slope <- append(inflection.slope, result$inflection.slope)
  inflection.strain <- append(inflection.strain, result$inflection.strain)
  inflection.score <- append(inflection.score, result$inflection.score)
  fds.slope <- append(fds.slope, result$fds.slope)
  fds.strain <- append(fds.strain, result$fds.strain)
  fds.score <- append(fds.score, result$fds.score)
  
  plot.subtitle <- paste(
    "<b style=color:red;>Max:</b> ",
    round(result$max.slope, 1),
    "<br>",
    "<b style=color:DarkGreen;>Inflection:</b>",
    round(result$inflection.slope, 1),
    "<br>",
    "<b style='color:blue;'>FDS:</b>",
    round(result$fds.slope, 1),
    "<br>",
    "<b style='color:black;'>R-squared:</b>",
    round(result$r.squared, 2)
  )
  
  plot <- plot.plot(
    bone,
    layers = list(
      geom_segment(
        x = result$max.strain,
        xend = result$max.strain,
        y = 0,
        yend = max(bone$Stress * 0.80),
        color = "red"
      ),
      geom_segment(
        x = result$inflection.strain,
        xend = result$inflection.strain,
        y = 0,
        yend = max(bone$Stress * 0.80),
        color = "DarkGreen"
      ),
      geom_segment(
        x = result$fds.strain,
        xend = result$fds.strain,
        y = 0,
        yend = max(bone$Stress * 0.80),
        color = "blue"
      ),
      annotate(
        "text",
        x = result$max.strain,
        y = max(bone$Stress),
        label = round(result$max.score, 3),
        angle = 0,
        color = "red",
        size = 2,
        fontface = "bold"
      ),
      annotate(
        "text",
        x = result$inflection.strain,
        y = max(bone$Stress * 0.925),
        label = round(result$inflection.score, 3),
        angle = 0,
        color = "DarkGreen",
        size = 2,
        fontface = "bold"
      ),
      annotate(
        "text",
        x = result$fds.strain,
        y = max(bone$Stress * 0.85),
        label = round(result$fds.score, 3),
        angle = 0,
        color = "blue",
        size = 2,
        fontface = "bold"
      ),
      labs(subtitle = plot.subtitle)
    )
  )
  
  #print(plot)
  image.save(bone, plot, directory = "ymResults")
})
```

```{r}
results <- tibble(names, max.slope, inflection.slope, fds.slope,  max.strain, inflection.strain, fds.strain, max.score, inflection.score, fds.score, rsquared)
write_csv(results, "./data/youngs-modulus-results/results.csv")
```






